#!/usr/bin/env python3

import random
from turtle import Turtle, Screen

screen = Screen()
screen.setup(width=500, height=400)
is_race_on = False
user_bet = screen.textinput(title="Make your bet.", prompt="Which turtle will win the race? Enter a color: ")
colors = ["red", "orange", "yellow", "green", "blue", "purple"]

y_axis = -75
turtles = {}
for color in colors:
    turtles[color] = Turtle(shape="turtle")
    turtles[color].penup()
    turtles[color].color(color)
    turtles[color].goto(x=-230, y=y_axis)
    y_axis += 25

if user_bet:
    is_race_on = True

while is_race_on:
    for turtle in turtles:
        if turtles[turtle].xcor() > 230:
            is_race_on = False
            winning_color = turtle
            if winning_color == user_bet:
                print(f"You've won! The {winning_color} turtle is the winner!")
            else:
                print(f"You've lost. The {winning_color} turtle is the winner!")
            break
        random_distance = random.randint(0, 10)
        turtles[turtle].forward(random_distance)

screen.exitonclick()
